
default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>

staging:
  <<: *default

development:
  <<: *default
  database: my-rails-elm-project-development

test:
  <<: *default
  database: my-rails-elm-project-test

production:
  <<: *default
  database: my-rails-elm-project-production
